### ISSUE TITLE
Pacote nugget

### ISSUE THREAD

**Issue by Fabioh** [totalvoice/totalvoice-csharp#1]
Existe algum pacote Nuget pronto para o consumo da API de vocês?

Da mesma forma que existe uma implementação pronta no [NPMjs](https://www.npmjs.com/package/totalvoice-node)

**Comment by dilowagner** [comment]
Ola @Fabioh tudo bem?
Ainda nao, estamos finalizando essa lib...

Mas para algumas operacoes basicas, temos a versao antiga no link abaixo:
https://github.com/totalvoice/EvolineAPI-VisualStudio

**Comment by dilowagner** [comment]
Ola @Fabioh 
Liberamos a versao 1.0.1 - esta publicado no Nuget.org

Valeuuus!

**Comment by Fabioh** [comment]
Show de bola 🎉🎉🎉🎉
